version: "3.9"
services:
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s
  it-test-runner:
    build:
      dockerfile: Dockerfile.jlink
      target: base
      context: .
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_DATABASE_USER: "postgres"
      JDBC_DATABASE_PASSWORD: "postgres"
    depends_on:
      db:
        condition: service_healthy
