version: "3.9"
services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      #- POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rest:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_DATABASE_USER: "postgres"
      JDBC_DATABASE_PASSWORD: "postgres"
      PORT: 8080
    depends_on:
      - db
