version: "3.9"
services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      #- POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres