version: "3.9"
services:
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rest:
    restart: on-failure
    build:
      dockerfile: Dockerfile.jlink
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_DATABASE_USER: "postgres"
      JDBC_DATABASE_PASSWORD: "postgres"
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
  it-test-runner:
      build:
        dockerfile: Dockerfile.base
      environment:
        JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
        JDBC_DATABASE_USER: "postgres"
        JDBC_DATABASE_PASSWORD: "postgres"
      depends_on:
        db:
          condition: service_healthy



