CREATE SEQUENCE IF NOT EXISTS CHECKLIST_SEQUENCE START 1 INCREMENT 1;

CREATE TYPE LIST_TYPE AS ENUM ('EXISTING_ITEMS_LIST', 'ITEMS_LIST');
CREATE TYPE ITEM_TYPE AS ENUM ('EXISTING_ITEM', 'LIST_ITEM');

CREATE TABLE IF NOT EXISTS ITEMS_LIST
(
    ID
    BIGINT
    PRIMARY
    KEY,
    NAME
    VARCHAR
(
    255
) NOT NULL,
    LIST_TYPE LIST_TYPE
    );

CREATE TABLE IF NOT EXISTS ITEM
(
    ID
    BIGINT
    PRIMARY
    KEY,
    NAME
    VARCHAR
    NOT
    NULL,
    ITEMS_LIST_ID
    BIGINT
    NOT
    NULL,
    ORDER_NUMBER
    BIGINT
    NOT
    NULL,
    CONSTRAINT
    CHECKLIST_ID_FK
    FOREIGN
    KEY
(
    ITEMS_LIST_ID
) REFERENCES ITEMS_LIST
(
    ID
) ON DELETE CASCADE
    );

-- CREATE TABLE IF NOT EXISTS BASE_ITEM_ROW
-- (
--     ID           BIGINT PRIMARY KEY,
--     NAME         VARCHAR,
--     ITEM_ID BIGINT NOT NULL,
--     CONSTRAINT  ITEM_ID_FK FOREIGN KEY (ITEM_ID)
--         REFERENCES ITEM (ID) ON DELETE CASCADE
-- );

CREATE TABLE IF NOT EXISTS CHECKLIST_ITEM_PROPERTIES
(
    ID
    BIGINT
    NOT
    NULL,
    COMPLETED
    BOOL,
    ITEM_ID
    BIGINT,
    CONSTRAINT
    ITEM_ID_FK
    FOREIGN
    KEY
(
    ITEM_ID
) REFERENCES ITEM
(
    ID
) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS EXISTING_ITEM__PROPERTIES
(
    ID
    BIGINT
    NOT
    NULL,
    ITEM_ID
    BIGINT,
    CONSTRAINT
    ITEM_ID_FK
    FOREIGN
    KEY
(
    ITEM_ID
) REFERENCES ITEM
(
    ID
) ON DELETE CASCADE
    );


