security:
  enabled: false
server:
  experimental:
    http2:
      enable: true
      max-content-length: 16384
quarkus:
  http:
    cors:
      origins: *
      headers: accept, authorization, content-type, x-requested-with
      methods: *

